name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: write

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    if: ${{github.repository}} == ${{github.event.repository}}
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.3.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","style"]'
          add_label: "true"
          custom_labels: '{"feat": "feature", "fix": "bugfix", "docs": "documentation", "test": "test", "ci": "CI/CD", "refactor": "refactor", "perf": "performance", "chore": "chore", "wip": "WIP"}'
